# Generated by Django 3.1.6 on 2021-03-03 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('idno', models.CharField(default='', max_length=128)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
