# Generated by Django 3.1.7 on 2021-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210408_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='idno',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
